spring:
  profiles: 
    active: test
---    
spring:
  profiles: test
  application:
    name: wangou-config-test
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
---  
spring:
  profiles: prod
  application:
    name: wangou-config-prod
server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
    
