spring:
  profiles: 
    active: test
busi.ops: y    
---    
spring:
  profiles: test
  application:
    name: wangou-config-test
server:
  port: 8080

---  
spring:
  profiles: prod
  application:
    name: wangou-config-prod
server:
  port: 8088
    
